#此配置文件将保存要在所有文件之间共享的公共配置
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册服务器的位置

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8114/user/current
      token-info-uri: http://localhost:8114/oauth/check_token